# ==============================================================================
# Date : 20-06-2025
# File: config/config.yaml
# Description: Configuration for the pipeline.
# ==============================================================================
s3_buckets:
  raw_data: "s3://airline-ds-raw-data"
  staging_area: "s3://airline-ds-staging-area"
  processed_data: "s3://airline-ds-processed-data"

data_sources:
  # rcis:
  #   path: "rcis/all_multi_intent.csv"
  twcs:
    path: "twcs/twcs.csv"
  convo3k:
    path: "conversation-3k/Conversation.csv"
  
dask_npartitions: 4

# For PII detection (using simple regex as a placeholder)

pii_patterns:
  EMAIL: '\S*@\S*\s?'
  PNR: '[A-Z0-9]{6}' 
  PHONE: '\b(?:\d{3}[-.\s]?\d{3}[-.\s]?\d{4}|\(\d{3}\)\s*\d{3}[-.\s]?\d{4}|\d{10})\b'
  CC_NUMBER: '\b(?:\d{4}[-.\s]?){3}\d{4}\b'


preprocessing:
  remove_mentions: true
  mention_patterns: '@\w+'
  remove_urls: true
  url_patterns: 'http\S+|www\S+'
  remove_emojis: false
  lowercase: true
  min_words: 3

AIR_TRAVEL_BRANDS:
  - "AmericanAir"
  - "AirAsiaSupport"
  - "British_Airways"
  - "AirbnbHelp"
  - "nationalrailenq"
  - "Delta"
  - "VirginTrains"
  - "SouthwestAir"
  - "VirginAtlantic"
  - "AlaskaAir"
  - "VirginAmerica"
  - "JetBlue"
  - "askvisa"
  - "HotelTonightCX"
  - "Expedia"
  - "Bookingcom"
  - "flySFO"
  - "KLM"
  - "Lufthansa"
  - "SingaporeAir"
  - "Qantas"
  - "Emirates"
  - "Qatar Airways"
  - "HiltonSuggests"
